const GET_ALL_RECEIPTS = 'GET_ALL_RECEIPTS';
const DELETE_RECEIPT = 'DELETE_RECEIPT';
const ADD_RECEIPT = 'ADD_RECEIPT';
const UPDATE_RECEIPT = 'UPDATE_RECEIPT';
const OPEN_ADD_FORM = 'OPEN_ADD_FORM';
const CLOSE_ADD_FORM = 'CLOSE_ADD_FORM';
const OPEN_UPDATE_FORM = 'OPEN_UPDATE_FORM';
const CLOSE_UPDATE_FORM = 'CLOSE_UPDATE_FORM';
const OPEN_REGISTER_FORM = 'OPEN_REGISTER_FORM';
const CLOSE_REGISTER_FORM = 'CLOSE_REGISTER_FORM';
const OPEN_AUTH_FORM = 'OPEN_AUTH_FORM';
const CLOSE_AUTH_FORM = 'CLOSE_AUTH_FORM';
const OPEN_MENU = 'OPEN_MENU';
const CLOSE_MENU = 'CLOSE_MENU';
const LOG_IN = 'LOG_IN';
const LOG_OUT = 'LOG_OUT';
const GET_CURRENT_USER_DATA = 'GET_CURRENT_USER_DATA';
const CLEAN_CURRENT_USER_DATA = 'CLEAN_CURRENT_USER_DATA';
const GET_DOCTORS_LIST = 'GET_DOCTORS_LIST';
const CLEAN_DOCTORS_LIST = 'CLEAN_DOCTORS_LIST';

export {
    GET_ALL_RECEIPTS,
    DELETE_RECEIPT,
    ADD_RECEIPT,
    UPDATE_RECEIPT,
    OPEN_ADD_FORM,
    CLOSE_ADD_FORM,
    OPEN_UPDATE_FORM,
    CLOSE_UPDATE_FORM,
    OPEN_AUTH_FORM,
    OPEN_REGISTER_FORM,
    CLOSE_AUTH_FORM,
    CLOSE_REGISTER_FORM,
    LOG_IN,
    LOG_OUT,
    GET_CURRENT_USER_DATA,
    CLEAN_CURRENT_USER_DATA,
    GET_DOCTORS_LIST,
    CLEAN_DOCTORS_LIST,
    OPEN_MENU,
    CLOSE_MENU
}