const GET_ALL_PRESCRIPTIONS = 'GET_ALL_PRESCRIPTIONS';
const DELETE_PRESCRIPTION = 'DELETE_PRESCRIPTION';
const ADD_PRESCRIPTION = 'ADD_PRESCRIPTION';
const UPDATE_PRESCRIPTION = 'UPDATE_PRESCRIPTION';
const OPEN_ADD_FORM = 'OPEN_ADD_FORM';
const CLOSE_ADD_FORM = 'CLOSE_ADD_FORM';
const OPEN_UPDATE_FORM = 'OPEN_UPDATE_FORM';
const CLOSE_UPDATE_FORM = 'CLOSE_UPDATE_FORM';
const OPEN_REGISTER_FORM = 'OPEN_REGISTER_FORM';
const CLOSE_REGISTER_FORM = 'CLOSE_REGISTER_FORM';
const OPEN_AUTH_FORM = 'OPEN_AUTH_FORM';
const CLOSE_AUTH_FORM = 'CLOSE_AUTH_FORM';
const OPEN_MENU = 'OPEN_MENU';
const CLOSE_MENU = 'CLOSE_MENU';
const LOG_IN = 'LOG_IN';
const LOG_OUT = 'LOG_OUT';
const GET_CURRENT_USER_DATA = 'GET_CURRENT_USER_DATA';
const CLEAN_CURRENT_USER_DATA = 'CLEAN_CURRENT_USER_DATA';
const GET_DOCTORS_LIST = 'GET_DOCTORS_LIST';
const CLEAN_DOCTORS_LIST = 'CLEAN_DOCTORS_LIST';
const GET_PATIENTS_LIST_FOR_DOCTOR = 'GET_PATIENTS_LIST_FOR_DOCTOR';
const GET_PATIENT_DATA_FOR_DOCTOR = 'GET_PATIENT_DATA_FOR_DOCTOR';
const GET_DAILY_PRESCRIPTIONS = 'GET_DAILY_PRESCRIPTIONS';
const CHANGE_PRESCRIPTION_STATUS = 'CHANGE_PRESCRIPTION_STATUS';

export {
    GET_ALL_PRESCRIPTIONS,
    DELETE_PRESCRIPTION,
    ADD_PRESCRIPTION,
    UPDATE_PRESCRIPTION,
    OPEN_ADD_FORM,
    CLOSE_ADD_FORM,
    OPEN_UPDATE_FORM,
    CLOSE_UPDATE_FORM,
    OPEN_AUTH_FORM,
    OPEN_REGISTER_FORM,
    CLOSE_AUTH_FORM,
    CLOSE_REGISTER_FORM,
    LOG_IN,
    LOG_OUT,
    GET_CURRENT_USER_DATA,
    CLEAN_CURRENT_USER_DATA,
    GET_DOCTORS_LIST,
    CLEAN_DOCTORS_LIST,
    OPEN_MENU,
    CLOSE_MENU,
    GET_PATIENTS_LIST_FOR_DOCTOR,
    GET_PATIENT_DATA_FOR_DOCTOR,
    GET_DAILY_PRESCRIPTIONS,
    CHANGE_PRESCRIPTION_STATUS
}